[package]
name = "whatsys"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]
edition = "2018"
description = "Determine the kernel version"
license = "MIT"

[dependencies]
cfg-if = "1.0.0"
libc = "0.2.88"

[build-dependencies]
cc = "1.0.67"
